name: Sequnce-Job
on: workflow_dispatch

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: verify
        run: echo "verify job"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo "build job"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "deployment job"
